name: flutter_ihm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_reactive_ble: ^5.4.0
  permission_handler: 12.0.1
  flutter_blue_plus: ^1.31.8
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
